openapi: 3.0.0
info:
  contact:
    name: Itblog API
  description: Itblog API
  version: 1.0.0
  title: itblog api
servers:
  - url: 'http://localhost:5000/api'
    description: local
  - url: 'https://itblog/api'
    description: prd
paths:
  /auth/signup:
    post:
      summary: signup
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '200':
          description: 200 response
        '400':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/signin:
    post:
      summary: signin
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'
        '404':
          description: 404 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  parameters:
    Page:
      name: page
      in: query
      description: page number
      schema:
        type: integer
    Limit:
      name: limit
      in: query
      description: limit number
      schema:
        type: integer
    SearchWord:
      name: search_word
      in: query
      description: search work
      schema:
        type: string
  schemas:
    SignUpRequest:
      type: object
      description: SignUp request
      properties:
        name:
          type: string
          description: Name
        username:
          type: string
          description: Username
        email:
          type: string
          description: Email
        password:
          type: string
          description: Password
        role:
          type: string
          description: admin or remove role field
      required:
        - name
        - username
        - email
        - password
      x-example:
        example:
          value:
            name: admin
            username: admin
            email: admin@gmail.com
            password: admin123
            role: ROLE_ADMIN
    SignInRequest:
      type: object
      description: SignIn request
      properties:
        usernameOrEmail:
          type: string
          description: Username or email in order to login
        password:
          type: string
          description: Password login
      required:
        - usernameOrEmail
        - password
      x-example:
        example:
          value:
            usernameOrEmail: admin@gmail.com
            password: admin123
    ErrorResponse:
      type: object
      description: Error response
      properties:
        success:
          type: string
          description: false
        message:
          type: string
      required:
        - success
        - message
      example:
        value:
          success: false
          message: string
    SignInResponse:
      type: object
      description: SignIn response
      properties:
        accessToken:
          type: string
          description: Access token JWT
        tokenType:
          type: string
          description: Token type
      required:
        - accessToken
        - tokenType
      x-example:
        example:
          value:
            accessToken: string
            tokenType: Bearer


